* Haskell learning
** Configure VirtualBox to view local folders
   Use the following instructions to configure Shared Folders in VirtualBox
   1) Devices | Shared Folders 
   2) Add a new shared folder. Folder name = "portfolios"
   3) This will create a new mount point in /media/sf_portfolios
   4) It should be accessible by all users in group "vboxsf".
   5) sudo adduser john vboxsf , to add john to vboxsf group.

** How to push to github
   Use SPC g s to open a git status buffer. Then use s and u to stage and unstage files.
   SPC g m c c to open a commit message buffer, and C-c C-c to commit the changes.
   Finally, use SPC g m P u to push to origin/master
** TODO create a job to download share data from Google spreadsheets 
** TODO create new job to store that data in a file
*** data should come from Google spreadsheets (see finance functions)
*** think about unit testing
** TODO create a job to read share data from file into object 
** TODO Change name of existing jobs to something better
*** ParseCsvMain -> PrintPerformanceStats [[file:app/ParseCsvMain.hs][ParseCsvMain]]

** TODO create a job to extract dividend data from hl website
*** for example:[[https://www.hl.co.uk/shares/shares-search-results/l/lloyds-banking-group-plc-ordinary-10p/dividends][ Lloyds Dividend information]] 
*** Get content from website and write code to parse it and extract out relevant data.


* Type ideas

#+BEGIN_SRC haskell
  data Dividend = Dividend
    { date     :: Day
    , currency :: String
    , amount   :: Double
    }

  -- Both instances of "Security", but extract that class out later
  data Stock = Stock {name :: String}
  data Fund = Fund {name :: String}

  -- start off with separate functions and then see if there is any commonality
  stockDividends :: Stock -> [Dividend]
  fundDividends :: Fund -> [Dividend]
#+END_SRC

